[package]
name = "photo-tools"
version = "0.1.0"
authors = ["Szabolcs Berecz <szabolcs.berecz@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.30.0"
error-chain = "0.11.0"
lazy_static = "1.0.0"
regex = "1.5.5"
structopt = "0.2"
walkdir = "2.0.1"
